.mode	columns
.headers	on
.nullvalue	NULL


SELECT * FROM COMENTARIO WHERE COMENTARIO.Id_Coment = 6;
SELECT * FROM CLASSIFICACAOCOMENT WHERE CLASSIFICACAOCOMENT.LogUser_Id = 4 AND CLASSIFICACAOCOMENT.Id_Coment = 6; 

-- Alterar tabela
UPDATE CLASSIFICACAOCOMENT 
SET Tipo = 'Like'
WHERE LogUser_Id = 4 AND Id_Coment = 6;


--Verificar num likes e dislikes comentario e reacao
SELECT * FROM COMENTARIO WHERE COMENTARIO.Id_Coment = 6;
SELECT * FROM CLASSIFICACAOCOMENT WHERE CLASSIFICACAOCOMENT.LogUser_Id = 4 AND CLASSIFICACAOCOMENT.Id_Coment = 6; 